### ISSUE TITLE
Catch all these exceptions

### ISSUE THREAD

**Issue by notatallshaw** [notatallshaw/arandabot#28]
I've been running the bot for a while and come across all these exceptions

**Comment by notatallshaw** [comment]
Successfully submitted NEW WORLD BETRAYAL (MariCraft)
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    main()
  File "main.py", line 16, in main
    arandabot.arandabot(settings=settings)
  File "C:\Users\Damian\Documents\arandabot - test\arandabot.py", line 64, in ar
andabot
    link='https://www.youtube.com/watch?v='+YTid)
  File "C:\Users\Damian\Documents\arandabot - test\redditsubmissions.py", line 7
7, in submitContent
    print "Successfully submitted " + title
  File "C:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2026' in position
 42: character maps to <undefined>

**Comment by notatallshaw** [comment]
Failed to login to Reddit
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    main()
  File "main.py", line 16, in main
    arandabot.arandabot(settings=settings)
  File "C:\Users\Damian\Documents\arandabot - test\arandabot.py", line 48, in arandabot
    r = redditsubmissions.redditsubmissions(settings=reddit_settings)
  File "C:\Users\Damian\Documents\arandabot - test\redditsubmissions.py", line 23, in **init**
    self.reddit = self.getReddit()
  File "C:\Users\Damian\Documents\arandabot - test\redditsubmissions.py", line 29, in getReddit
    r.login(self.set.username, self.set.password)
  File "C:\Users\Damian\Documents\arandabot - test\praw__init__.py", line 1330, in login
    self.request_json(self.config['login'], data=data)
  File "C:\Users\Damian\Documents\arandabot - test\praw\decorators.py", line 163, in wrapped
    return_value = function(reddit_session, _args, *_kwargs)
  File "C:\Users\Damian\Documents\arandabot - test\praw__init__.py", line 557,in request_json
    retry_on_error=retry_on_error)
  File "C:\Users\Damian\Documents\arandabot - test\praw__init__.py", line 399,in _request
    _raise_response_exceptions(response)
  File "C:\Users\Damian\Documents\arandabot - test\praw\internal.py", line 178,in _raise_response_exceptions
    response.raise_for_status()
  File "C:\Users\Damian\Documents\arandabot - test\requests\models.py", line 795, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable

**Comment by notatallshaw** [comment]
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    main()
  File "main.py", line 16, in main
    arandabot.arandabot(settings=settings)
  File "C:\Users\Damian\Documents\arandabot - test\arandabot.py", line 55, in arandabot
    yt.getNewestVideos(yt_settings)
  File "C:\Users\Damian\Documents\arandabot - test\ytvideos.py", line 305, in getNewestVideos
    batch.execute()
  File "C:\Users\Damian\Documents\arandabot - test\oauth2client\util.py", line 132, in positional_wrapper
    return wrapped(_args, *_kwargs)
  File "C:\Users\Damian\Documents\arandabot - test\apiclient\http.py", line 1292, in execute
    self._execute(http, self._order, self._requests)
  File "C:\Users\Damian\Documents\arandabot - test\apiclient\http.py", line 1242, in _execute
    raise HttpError(resp, content, uri=self._batch_uri)
apiclient.errors.HttpError: <HttpError 502 when requesting https://www.googleapis.com/batch returned "Bad Gateway">

**Comment by notatallshaw** [comment]
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    main()
  File "main.py", line 16, in main
    arandabot.arandabot(settings=settings)
  File "C:\Users\Damian\Documents\arandabot - prod\arandabot.py", line 55, in arandabot
    yt.getNewestVideos(yt_settings)
  File "C:\Users\Damian\Documents\arandabot - prod\ytvideos.py", line 296, in getNewestVideos
    self.youtube = self.initilize_youtube(settings)
  File "C:\Users\Damian\Documents\arandabot - prod\ytvideos.py", line 117, in initilize_youtube
    http=credentials.authorize(httplib2.Http()))
  File "C:\Python27\lib\site-packages\oauth2client\util.py", line 132, in positional_wrapper
    return wrapped(_args, *_kwargs)
  File "C:\Python27\lib\site-packages\apiclient\discovery.py", line 198, in build
    raise HttpError(resp, content, uri=requested_url)
apiclient.errors.HttpError: <HttpError 500 when requesting https://www.googleapis.com/discovery/v1/apis/youtube/v3/rest returned "Backend Error">
